# Generated by Django 2.2.22 on 2021-06-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20210529_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emir',
            old_name='ağırlık_alt_limit',
            new_name='fm200bosagirlikmaxdeger',
        ),
        migrations.RenameField(
            model_name='emir',
            old_name='ağırlık_üst_limit',
            new_name='fm200bosagirlikmindeger',
        ),
        migrations.AddField(
            model_name='emir',
            name='fm200dolummiktarimaxdeger',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='emir',
            name='fm200dolummiktarimindeger',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
