# Generated by Django 2.2.22 on 2021-06-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20210604_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='valf_fm200',
            name='bar',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
