# Generated by Django 2.2.22 on 2021-06-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_valf_fm200_bar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valf_havuz',
            name='havuz_kurlenme_baslangic_tarihi',
        ),
        migrations.RemoveField(
            model_name='valf_havuz',
            name='havuz_kurlenme_bitis_tarihi',
        ),
        migrations.RemoveField(
            model_name='valf_havuz',
            name='havuz_kurlenme_personel',
        ),
        migrations.RemoveField(
            model_name='valf_havuz',
            name='havuz_parti_no',
        ),
    ]
