# Generated by Django 2.2.22 on 2021-06-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20210606_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valf_havuz',
            name='uygunluk',
            field=models.BooleanField(default=False),
        ),
    ]
