# Generated by Django 2.2.22 on 2021-06-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20210606_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valf_final_montaj',
            old_name='etiket_seri_no',
            new_name='uretim_seri_no',
        ),
    ]
