# Generated by Django 2.2.22 on 2021-06-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20210608_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valf_final_montaj',
            name='urun_seri_no',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
