# Generated by Django 2.2.22 on 2021-06-15 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20210613_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valf_fm200',
            name='uygunluk',
        ),
    ]
