# Generated by Django 2.2.22 on 2021-06-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_remove_valf_fm200_uygunluk'),
    ]

    operations = [
        migrations.AddField(
            model_name='valf_final_montaj',
            name='agirlik',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
