# Generated by Django 2.2.22 on 2021-06-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_valf_final_montaj_agirlik'),
    ]

    operations = [
        migrations.AddField(
            model_name='valf_fm200',
            name='vsn',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='valf_govde',
            name='vsn',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
