# Generated by Django 2.2.22 on 2021-06-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_auto_20210617_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='sibop_lot_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
