# Generated by Django 2.2.22 on 2021-06-20 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_test_sibop_lot_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='sibop_lot_no',
        ),
    ]
