# Generated by Django 2.2.22 on 2021-06-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_remove_test_sibop_lot_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='valf_montaj',
            name='sibop',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
